public abstract with sharing class New1 {

    decimal length;
    Decimal breadth;

    Public decimal GetLength(){
        return length;
    }

    Public void setLength(Decimal Length){
        this.length = length;

    }
    Public decimal GetBreadth(){
        return breadth;
    }

    Public void setBreadth(Decimal Breadth){
        this.Breadth = Breadth;

    }

    public abstract void Getarea();
    public abstract  void getPerimeter();

    
}