public with sharing class  VegetableProducts implements Product{

    Decimal Discount;
    Decimal NetPrice;

   


    public String getProductName(string Name){
        
        return name;
        


    }
    public Decimal getDiscount(Decimal discount){
        this.discount = discount;
        
        return Discount;

    }
    public Decimal getPrice(Decimal Price){
        
        
        return Netprice = price-(price*Discount);
        
        
    }
    
}