public class m9h2 {
    public static void m9h2(String name){
          system.debug('Print '+ name);
        try{
            System.debug('This is try block');
            system.debug('Contains '+ name.contains('a'));
        }
        catch(Exception exc){
            system.debug('This is catch block');
            
        }
        
        system.debug('Print '+ name);
        
    
    }
}